# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-30 10:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20161229_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionmodel',
            name='image',
            field=models.ImageField(null=True, upload_to='News/static/img', verbose_name='Изображение'),
        ),
    ]
